version: "3.1"
services:
  # seata服务1
  seata-server:
    image: seataio/seata-server:1.3.0
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      # 指定seata服务启动端口
      - SEATA_PORT=8091
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      - SEATA_IP=124.223.112.64
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 需要把file.conf和registry.conf都放到./seata-server/config文件夹中
      - "./seata-server/config:/root/seata-config"
