version: "3.1"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    volumes:
      #新建日志存放目录
      - ./cluster-logs/nacos1:/home/nacos/logs
      #自己自定义配置,可不要
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8847:8848"
      - "9555:9555"
    env_file:
      #数据库的相关信息,用于服务配置等持久化
      - ./env/nacos-server.env
    restart: always
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:latest
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    env_file:
      - ./env/nacos-server.env
    restart: always
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:latest
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
    env_file:
      - ./env/nacos-server.e